Reduce package size
flathub/org.kde.kate pull request #51
Opened 2024-06-05 23:33 UTC by yakushabb

- To be tested carefully.

2024-06-05 23:36 UTC, yakushabb commented
Package size might be redeced from 36.7MB to 16.4MB due to removing share/doc folder



![image](https://github.com/flathub/org.kde.kate/assets/161761531/eb316de9-b620-4044-8b61-4904f09591dd)

![image](https://github.com/flathub/org.kde.kate/assets/161761531/b7aa84aa-4683-4903-b3f3-e10ba4d6a6be)

2024-06-06 21:14 UTC, tsdgeos commented
Why are you removing the application documentation?

2024-06-06 21:21 UTC, yakushabb commented
Kate handbook opens the following page in the browser: https://docs.kde.org/stable5/en/kate/kate/index.html

Are the documentations visible offline?

2024-06-06 21:46 UTC, tsdgeos commented
I guess that's a bug in our flatpak system [*], the normal/non-flathub kate opens the documentation locally.

[*] I guess the runtime should package khelpcenter

2024-06-06 23:05 UTC, yakushabb commented
non-flatpak version from Fedora Rawhide also opens the same page.

![Ekran Görüntüsü - 2024-06-07 02-03-59](https://github.com/flathub/org.kde.kate/assets/161761531/603abede-f69d-469d-940a-930e74521f51)

2024-06-07 07:39 UTC, tsdgeos commented
That's because you don't have khelpcenter installed

2024-06-07 11:08 UTC, travier requested changes
If the docs don't work we should fix that. Some of the cleanups we can do, the others I don't think we can.

2024-06-07 11:08 UTC, travier commented on org.kde.kate.json
> +        "/bin/kwrite",
OK

2024-06-07 11:08 UTC, travier commented on org.kde.kate.json
> +        "/share/zsh",
OK

2024-06-07 11:08 UTC, travier commented on org.kde.kate.json
> +        "/share/man",
OK

2024-06-07 11:08 UTC, travier commented on org.kde.kate.json
> +        "/share/metainfo/org.kde.markdownpart.metainfo.xml",
OK, but that's super small.

2024-06-07 12:35 UTC, yakushabb commented
OK?
```
"/bin/kwrite"
"/share/zsh",
"/share/man",
```

Trivial

```
"/share/metainfo/org.kde.kwrite.appdata.xml",
"/share/metainfo/org.kde.konsole.appdata.xml",
"/share/metainfo/org.kde.markdownpart.metainfo.xml",
```

Not OK?

```
"/share/doc",
"/share/kateproject",
"/share/knsrcfiles",
"/share/qlogging-categories6",
"/share/knotifications6",
"/share/kio",
"/share/kconf_update",
"/etc",
"/lib/kconf_update_bin"
```

2024-06-07 14:52 UTC, travier commented
Yes. Agree that the GitHub issues made than more confusing than I expected

2024-06-07 15:18 UTC, yakushabb commented
Not impressive!

![resim](https://github.com/flathub/org.kde.kate/assets/161761531/aeb116a8-86b8-484e-b3d2-d7d463d48d4f)

2024-06-10 09:12 UTC, travier approved these changes

2024-06-10 20:08 UTC, tsdgeos commented
ok for me too i guess

2024-06-17 12:15 UTC, bbhtt commented
bot, build

2024-06-17 14:07 UTC, travier approved these changes

2024-06-17 14:07 UTC, merged